---
CIFAR100:
  # datapath: ''
  ai85simplenet:
    threshold: 100
    epoch: 2
MNIST:
  # datapath = ""
  ai85netextrasmall:
    threshold: 1000
    epoch: 3

  ai85net5:
    threshold: -500
    epoch: 4
