name: Trigger External Workflow
# Repo A
on:
  pull_request:
    types: [opened]

jobs:
  trigger_dispatch:
    runs-on: self-hosted
    steps:
      - name: Dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.regression_test_token }}
          repository: asyatrhl/ai8x-regression
          branch: main
          event-type: 'repo-a-pull-request'
