name: Listen for pull requests

on:
  repository_dispatch:
    types: [incoming_pull_request]

jobs:
  listen:
    runs-on: self-hosted

    steps:
    - name: Your custom action
      run: echo "A new pull request has been received"
