name: auto-testing
on: [push]
jobs:
  build:
    #runs-on: [ubuntu-latest]
    runs-on: self-hosted
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
        name: trial-check
        with:
          submodules: recursive

      - name: Setup Pyenv and Install Dependencies
        uses: gabrielfalcao/pyenv-action@v13
        with:
          default: 3.8.11
          
      - name: create venv
        run: pyenv local 3.8.11 & python3 -m venv venv --prompt ai8x-training   
      
      - name: activate venv
        run: source venv/bin/activate
      
      - name: install dep
        run: pip3 install -U pip wheel setuptools && pip3 install -r requirements-cu11.txt
         
      - name: Last Develop Check
        run: python last_dev.py
        
      - name: Create Test Script
        run: python create_test_script.py

      - name: Run Training Scripts
        run: bash /home/asyaturhal/actions-runner/_work/ai8x-training/ai8x-training/scripts/output_file.sh
      
      #- name: Create ONNX script
       # run: python create_onnx_scripts.py
        
      #- name: Run ONNX
       # run: bash /home/asyaturhal/actions-runner/_work/ai8x-training/ai8x-training/scripts/onnx_scripts.sh  
      
      - name: Change Log Names
        run: python log_name.py
        
      - name: Save Log Files
        run: cp -r /home/asyaturhal/actions-runner/_work/ai8x-training/ai8x-training/logs/ /home/asyaturhal/desktop/ai/test_logs/$(date +"%Y-%m-%d-%k-%M-")

      - name: Log Diff
        run: python log_comparison.py
        
      - name: Test Results
        run: python pass_fail.py
