name: Trigger External Workflow

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the repository is a fork
        id: check-fork
        run: |
          IsSpecificRepository=${{ github.repository == 'asyatrhl/ai8x-training' }}
          IsDevelopBranch=${{ github.ref == 'refs/heads/main_test_fork' }}
          echo "IsSpecificRepository=${IsSpecificRepository}"
          echo "IsDevelopBranch=${IsDevelopBranch}"
        shell: bash

      - name: Set up environment
        if: steps.check-repository-branch.outputs.IsSpecificRepository == 'true' && steps.check-repository-branch.outputs.IsDevelopBranch == 'true'
        run: |
          PR_Branch=${{ github.event.pull_request.head.ref }}
          Repository=${{ github.repository }}
          PR_Number=${{ github.event.pull_request.number }}
          PR_Sha=${{ github.event.pull_request.head.sha }}
          echo "PR_Branch: $PR_Branch"
          echo "Repository: $Repository"
          echo "PR_Number: $PR_Number"
          echo "PR_Sha: $PR_Sha"

      - name: Dispatch event
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.REGRESSION }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/asyatrhl/ai8x-regression/dispatches" \
            -d '{"event_type": "repo-pull-request", "client_payload": {"PR_Branch": "${{ github.event.pull_request.head.ref }}", "Repository": "${{ github.repository }}","PR_Number": "${{ github.event.pull_request.number }}","PR_Sha": "${{ github.event.pull_request.head.sha }}" }'
