name: auto-testing
on: [push]
jobs:
  build:
    runs-on: self-hosted
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
        name: trial-check
        with:
          submodules: recursive
