---
name: auto-testing
on:
  - push
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 345600
    steps:
      - name: Checkout rotx-maxim/ai8x-training
        uses: actions/checkout@v2
        with:
          repository: rotx-maxim/ai8x-training
          ref: pytorch-2.0
          submodules: recursive
      - name: Checkout MaximIntegratedAI/ai8x-training
        uses: actions/checkout@v2
        with:
          repository: MaximIntegratedAI/ai8x-training
          ref: pytorch-2.0
          submodules: recursive         
      - name: Checkout Test Codes
        uses: actions/checkout@v2
        with:
          repository: asyatrhl/ai8x-training-test-codes
          ref: main
          path: test_codes
      - name: Checkout Test Codes
        uses: actions/checkout@v2
        with:
          repository: asyatrhl/regression-test
          ref: main
          path: last-dev
      - name: Setup Pyenv and Install Dependencies
        uses: gabrielfalcao/pyenv-action@v13
        with:
          default: 3.8.11
      - name: Create Venv
        run: pyenv local 3.8.11 & python3 -m venv venv --prompt ai8x-training
      - name: Activate Venv
        run: source venv/bin/activate
      - name: Install Dependencies
        run: pip3 install -U pip wheel setuptools && pip3 install -r
          ./test_codes/requirements-cu11.txt
      - name: torchmetrics
        run: pip install torchmetrics
      - name: Check Pytorch version
        run: pip list | grep torch
      - name: Check Numpy version
        run: pip show numpy --version
      - name: deneme
        run: python3 train.py --epochs 15 --optimizer Adam --lr 0.001 --wd 0 --deterministic --compress policies/schedule_kws20.yaml --model ai87kws20netv3 --dataset KWS_20 --confusion --device MAX78002 --name ai87kws20netv3-KWS_20 --data /data_ssd "$@"
#       - name: Last Develop Check
#         run: python ./test_codes/last_dev.py --testconf ./last-dev/test_config.yaml
      - name: Create Test Script
        run: python ./test_codes/create_test_script.py --testconf ./last-dev/test_config.yaml
#       - name: Run Training Scripts
#         run: bash
#           /home/asyaturhal/desktop/ai/test_scripts/output_file.sh
#       - name: Save Log Files
#         run: cp -r
#           /home/asyaturhal/actions-runner/_work/ai8x-training/ai8x-training/logs/
#           /home/asyaturhal/desktop/ai/test_logs/$(date +"%Y-%m-%d-%k-%M-")
#       - name: Log Diff
#         run: python ./test_codes/log_comparison.py
#       - name: Test Results
#         run: python ./test_codes/pass_fail.py --testconf ./last-dev/test_config.yaml
#       - name: Create ONNX script
#         run: python ./test_codes/create_onnx_scripts.py --testconf ./last-dev/test_config.yaml
#       - name: Run ONNX
#         run: bash
#           /home/asyaturhal/actions-runner/_work/ai8x-training/ai8x-training/scripts/onnx_scripts.sh
